@startuml
skinparam monochrome true
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam DefaultFontName arial
skinparam DefaultFontSize 12
skinparam ClassFontStyle bold
skinparam linetype ortho
skinparam dpi 200
hide empty fields
hide empty methods
hide circle

class BufferStop {
 id: string
 dangerPoints: *DangerPoint[0..*]
 bsType: BufferStopType
}

class Switch {
 id: string
 foulingPoints: *FoulingPoint[1..*]
 tipShift: double
 bladeLength: double
}

class Crossing {
 id: string
 foulingPoints: *FoulingPoint[1..*]
}

class LevelCrossing {
 id: string
 dangerPoints: *DangerPoint[1..*]
}

class BaliseGroup {
 id: string
 m_version: ss026.ETCSMVersions
 q_link: boolean
 q_updown: boolean
}

class Balise {
 id: string
 fixed: boolean
 m_dup: DuplicationType
 m_mcount: uint32
 n_pig: uint32
 verticallyOriented: boolean
 standardSize: boolean
 telegram: bytes
 telegramChecksum: string
 sleeperFastening: string
 baliseMountingSystem: string
 designType: string
 <s>kmReferenceMarker: *KilometricPost0..1</s>
}

class Sleepers {
 id: string
 sleepersType: SleepersType
}

class DangerPoint {
 id: string
 name: string
}

class FoulingPoint {
 id: string
 name: string[0..1]
 <s>clearancePoint: uint32</s>
}

class EngArea {
 <b>onTopoArea: *infra.TopoArea</b>
 defaultSleepersType: SleepersType
 <s>id: string</s>
}

class LocationAccuracyArea {
 <b>onTopoArea: *infra.TopoArea</b>
 <s>id: string</s>
}

class BaliseAccuracy {
 <b>balise: *infra.Balise</b>
 accuracy: uint32
 <s>baliseId: string</s>
}

class EtcsMarkerAccuracy {
 <b>etcsMarker: *infra.ETCSMarker</b>
 accuracy: uint32
 <s>markerId: string</s>
}

class StopLocationAccuracy {
 <b>stopLocation: *infra.StopLocation</b>
 accuracy: uint32
 <s>stopLocationId: string</s>
}

class NationalBorderAccuracy {
 <b>nationalBorder: *infra.NationalBorder</b>
 accuracy: uint32
 <s>nationalBorderId: string</s>
}

class BufferStopAccuracy {
 <b>bufferStop: *infra.BufferStop</b>
 accuracy: uint32
 <s>bufferStopId: string</s>
}

class LinearElementKmSigns {
 <b>linearElement: *infra.LinearElement</b>
 <s>id: string</s>
}

class KilometricPost {
 pos: uint32
 kmPostName: string[0..1]
 kilometerNumber: uint32
}

class KmArea {
 <b>onTopoArea: *infra.TopoArea</b>
 <s>id: string</s>
}

class ETCSEngineering {
}

BufferStop *-- "1..*" infra.LinearElementSection
Balise *-- "0..*" ss026.BalisePacket
Sleepers *-- "1..*" infra.LinearElementSection
DangerPoint *-- "1" infra.TopologicalCoordinate
FoulingPoint *-- "1" infra.TopologicalCoordinate
EngArea *-- "0..*" Switch
EngArea *-- "0..*" Crossing
EngArea *-- "0..*" LevelCrossing
EngArea *-- "0..*" BaliseGroup
EngArea *-- "0..*" Balise
EngArea *-- "0..*" Sleepers
EngArea *-- "0..*" DangerPoint
EngArea *-- "0..*" FoulingPoint
EngArea *-- "0..*" BufferStop
LocationAccuracyArea *-- "*" BaliseAccuracy
LocationAccuracyArea *-- "*" EtcsMarkerAccuracy
LocationAccuracyArea *-- "*" StopLocationAccuracy
LocationAccuracyArea *-- "*" NationalBorderAccuracy
LocationAccuracyArea *-- "*" BufferStopAccuracy
LinearElementKmSigns *-- "*" KilometricPost
KmArea *-- "*" LinearElementKmSigns
ETCSEngineering *-- "*" EngArea
ETCSEngineering *-- "*" LocationAccuracyArea
ETCSEngineering *-- "*" KmArea
@enduml