@startuml
skinparam monochrome true
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam DefaultFontName arial
skinparam DefaultFontSize 12
skinparam ClassFontStyle bold
skinparam linetype ortho
skinparam dpi 200
hide empty fields
hide empty methods
hide circle

package "infrastructure" {
  class TopoArea {}
  class LinearElement {}
  class NetRelation {}
  class TopologicalCoordinate {}
  class NetPointReference {}
  class LinearElementSection {}
  class NetLinearReference {}
  class NetAreaReference {}
  class LinkedArea {}
  class GeometryArea {}
  class LinearElementGeometry {}
  class HorizontalSegment {}
  class HorizontalLine {}
  class HorizontalArc {}
  class HorizontalTransition {}
  class VerticalSegment {}
  class VerticalLine {}
  class VerticalArc {}
  class CantPoint {}
  class SampledGeometryArea {}
  class SampledLinearElementGeometry {}
  class SlopeSamplePoint {}
  class CantSamplePoint {}
  class CurveSamplePoint {}
  class Switch {}
  class SlipCrossing {}
  class Derailer {}
  class Crossing {}
  class BaliseGroup {}
  class Balise {}
  class PropertiesArea {}
  class LinearElementGauge {}
  class LinearElementLoadingGauge {}
  class TrackCondition {}
  class CurrentLimitation {}
  class PermittedBrakingDistance {}
  class TractionSystem {}
  class TrackUsageArea {}
  class LinearElementSpeedProfile {}
  class SpeedProfile {}
  class StaticSpeedLimit {}
  class SpecificStaticSpeedLimit {}
  class SpeedLimitCategory {}
  class AxleLoadSpeedProfile {}
  class ETCSMarker {}
  class StopLocation {}
  class StopTrainLimit {}
  class PlatformEdge {}
  class Platform {}
  class OperationalPoint {}
  class TravelTimeMeasurementPoint {}
  class TimingPoint {}
  class TPActiveObject {}
  class Tunnel {}
  class TunnelTube {}
  class Bridge {}
  class Underpass {}
  class TvpSection {}
  class TrainDetector {}
  class LevelCrossing {}
  class NationalBorder {}
  class BufferStop {}
  class FunctionalArea {}
  class Infrastructure {}
}

infrastructure.TopoArea -- infra.LinearElement: linearElements
infrastructure.TopoArea -- infra.NetRelation: netRelations
infrastructure.NetRelation -- infra.LinearElement: elementA
infrastructure.NetRelation -- infra.LinearElement: elementB
infrastructure.TopologicalCoordinate -- infra.LinearElement: onLinearElement
infrastructure.NetPointReference -- infra.TopologicalCoordinate: hasTopoCoordinate
infrastructure.LinearElementSection -- infra.LinearElement: onElement
infrastructure.NetLinearReference -- infra.TopologicalCoordinate: startsAt
infrastructure.NetLinearReference -- infra.TopologicalCoordinate: endsAt
infrastructure.NetLinearReference -- infra.LinearElement: hasSequence
infrastructure.NetAreaReference -- infra.NetLinearReference: includes
infrastructure.LinkedArea -- infra.NetLinearReference: includes
infrastructure.GeometryArea -- infra.LinearElementGeometry: linearElementGeometries
infrastructure.LinearElementGeometry -- infra.HorizontalSegment: horizontalAlignments
infrastructure.LinearElementGeometry -- infra.VerticalSegment: verticalAlignments
infrastructure.LinearElementGeometry -- infra.CantPoint: cantPoints
infrastructure.HorizontalSegment -- infra.HorizontalLine: horizontalSegmentLine
infrastructure.HorizontalSegment -- infra.HorizontalArc: horizontalSegmentArc
infrastructure.HorizontalSegment -- infra.HorizontalTransition: horizontalSegmentTransition
infrastructure.VerticalSegment -- infra.VerticalLine: verticalSegmentLine
infrastructure.VerticalSegment -- infra.VerticalArc: verticalSegmentArc
infrastructure.SampledGeometryArea -- infra.SampledLinearElementGeometry: sampledLinearElementGeometries
infrastructure.SampledLinearElementGeometry -- infra.SlopeSamplePoint: slopes
infrastructure.SampledLinearElementGeometry -- infra.CurveSamplePoint: curves
infrastructure.SampledLinearElementGeometry -- infra.CantSamplePoint: cants
infrastructure.Switch -- infra.NetRelation: pointLeft
infrastructure.Switch -- infra.NetRelation: pointRight
infrastructure.SlipCrossing -- infra.Switch: switches
infrastructure.SlipCrossing -- infra.Crossing: crossing
infrastructure.Derailer -- infra.NetPointReference: netPointReference
infrastructure.Crossing -- infra.TopologicalCoordinate: topologicalCoordinates
infrastructure.BaliseGroup -- infra.Balise: balises
infrastructure.Balise -- infra.TopologicalCoordinate: topologicalCoordinate
infrastructure.PropertiesArea -- infra.LinearElementSpeedProfile: linearElementSpeedProfiles
infrastructure.PropertiesArea -- infra.LinearElementGauge: linearElementGauges
infrastructure.PropertiesArea -- infra.LinearElementLoadingGauge: linearElementLoadingGauges
infrastructure.PropertiesArea -- infra.TrackCondition: trackConditions
infrastructure.PropertiesArea -- infra.CurrentLimitation: currentLimitations
infrastructure.PropertiesArea -- infra.PermittedBrakingDistance: permittedBrakingDistances
infrastructure.PropertiesArea -- infra.TractionSystem: tractionSystems
infrastructure.LinearElementGauge -- infra.LinearElementSection: linearElementSections
infrastructure.LinearElementLoadingGauge -- infra.LinearElementSection: linearElementSections
infrastructure.TrackCondition -- infra.LinearElementSection: linearElementSections
infrastructure.CurrentLimitation -- infra.LinearElementSection: linearElementSections
infrastructure.PermittedBrakingDistance -- infra.LinearElementSection: linearElementSections
infrastructure.TractionSystem -- infra.LinearElementSection: linearElementSections
infrastructure.TrackUsageArea -- infra.LinearElement: secondaryTracks
infrastructure.TrackUsageArea -- infra.LinearElement: shuntingTracks
infrastructure.TrackUsageArea -- infra.LinearElement: preferredSameDir
infrastructure.TrackUsageArea -- infra.LinearElement: preferredOppositeDir
infrastructure.LinearElementSpeedProfile -- infra.SpeedProfile: sameDirProfile
infrastructure.LinearElementSpeedProfile -- infra.SpeedProfile: oppositeDirProfile
infrastructure.SpeedProfile -- infra.StaticSpeedLimit: staticSpeedProfile
infrastructure.SpeedProfile -- infra.AxleLoadSpeedProfile: axleLoadSpeedProfiles
infrastructure.StaticSpeedLimit -- infra.SpecificStaticSpeedLimit: specificStaticSpeedLimits
infrastructure.SpecificStaticSpeedLimit -- infra.SpeedLimitCategory: specificLimitCategory
infrastructure.ETCSMarker -- infra.NetPointReference: netPointReference
infrastructure.StopLocation -- infra.NetPointReference: netPointReference
infrastructure.StopLocation -- infra.StopTrainLimit: stopTrainLimit
infrastructure.PlatformEdge -- infra.NetLinearReference: linearReference
infrastructure.PlatformEdge -- infra.StopLocation: stopLocations
infrastructure.Platform -- infra.PlatformEdge: platformEdges
infrastructure.OperationalPoint -- infra.TravelTimeMeasurementPoint: travelTimeMeasurementPoints
infrastructure.OperationalPoint -- infra.Platform: platforms
infrastructure.TravelTimeMeasurementPoint -- infra.TopologicalCoordinate: topologicalCoordinate
infrastructure.TimingPoint -- infra.TopologicalCoordinate: topologicalCoordinate
infrastructure.TimingPoint -- infra.TPActiveObject: activeObject
infrastructure.TPActiveObject -- infra.ETCSMarker: etcsMarker
infrastructure.TPActiveObject -- infra.StopLocation: stopLocation
infrastructure.TPActiveObject -- infra.TravelTimeMeasurementPoint: timeMeasurePoint
infrastructure.Tunnel -- infra.TunnelTube: tunnelTubes
infrastructure.TunnelTube -- infra.NetAreaReference: areaReference
infrastructure.Bridge -- infra.NetAreaReference: areaReference
infrastructure.Underpass -- infra.NetAreaReference: areaReference
infrastructure.TvpSection -- infra.NetAreaReference: linkedArea
infrastructure.TvpSection -- infra.TrainDetector: trainDetectors
infrastructure.TrainDetector -- infra.TopologicalCoordinate: topologicalCoordinate
infrastructure.LevelCrossing -- infra.NetAreaReference: areaReference
infrastructure.NationalBorder -- infra.TopologicalCoordinate: topologicalCoordinate
infrastructure.BufferStop -- infra.NetPointReference: netPointReference
infrastructure.FunctionalArea -- infra.OperationalPoint: opPoints
infrastructure.FunctionalArea -- infra.Switch: switches
infrastructure.FunctionalArea -- infra.SlipCrossing: slipCrossings
infrastructure.FunctionalArea -- infra.Derailer: derailers
infrastructure.FunctionalArea -- infra.Crossing: crossings
infrastructure.FunctionalArea -- infra.TrainDetector: trainDetectors
infrastructure.FunctionalArea -- infra.BaliseGroup: baliseGroups
infrastructure.FunctionalArea -- infra.ETCSMarker: etcsMarkers
infrastructure.FunctionalArea -- infra.StopLocation: stopLocations
infrastructure.FunctionalArea -- infra.Tunnel: tunnels
infrastructure.FunctionalArea -- infra.Bridge: bridges
infrastructure.FunctionalArea -- infra.Underpass: underpasses
infrastructure.FunctionalArea -- infra.TvpSection: tvps
infrastructure.FunctionalArea -- infra.LevelCrossing: levelCrossings
infrastructure.FunctionalArea -- infra.NationalBorder: nationalBorders
infrastructure.FunctionalArea -- infra.BufferStop: bufferStops
infrastructure.FunctionalArea -- infra.TimingPoint: timingPoints
infrastructure.Infrastructure -- infra.TopoArea: topoAreas
infrastructure.Infrastructure -- infra.GeometryArea: geometryAreas
infrastructure.Infrastructure -- infra.SampledGeometryArea: sampledGeometryAreas
infrastructure.Infrastructure -- infra.FunctionalArea: functionalAreas
infrastructure.Infrastructure -- infra.PropertiesArea: propertiesAreas
infrastructure.Infrastructure -- infra.TrackUsageArea: trackUsageAreas
@enduml
