@startuml
skinparam monochrome true
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam DefaultFontName arial
skinparam DefaultFontSize 12
skinparam ClassFontStyle bold
skinparam linetype ortho
skinparam dpi 200
hide empty fields
hide empty methods
hide circle

class ProtectedInfraElement << union >> {
 switch: *infra.Switch
 slipCrossing: *infra.SlipCrossing
 crossing: *infra.Crossing
 derailer: *infra.Derailer
 levelCrossing: *infra.LevelCrossing
}

class DriveProtectionSectionGroup {
 id: string
 name: string[0..1]
 dependenciesType: DPSDependencyType
 dpsgDependencies: uint32[0..*]
 runTime: uint32
}

class DriveProtectionSection {
 id: string
 name: string
 maxFlankProtectionSpeed: uint32
}

class AllocationSection {
 id: string
 name: string[0..1]
 dependencies: *AllocationSection[1..*]
}

class ControlledInfraElement << union >> {
 dpsGroup: *DriveProtectionSectionGroup
 tvpSection: *infra.TvpSection
}

class FieldObjectController {
 id: string
 <b>rastaId: string</b>
 <b>eulynxBaseline: string</b>
 version: uint32
 <b>belongsToAoc: *AreaOfControl</b>
 <s>rastaServerId: string</s>
 <s>rastaOCId: string</s>
}

class AreaOfControl {
 id: string
 name: string[0..1]
 <b>iPAddress: string</b>
 <b>rastaId: string</b>
 <b>portNumber: uint32</b>
}

class TrainProtectionArea {
 id: string
 <s>routes: Route0..*</s>
 <s>switches: Switch0..*</s>
 <s>transits: Transit0..*</s>
}

class TrainProtection {
}

DriveProtectionSectionGroup *-- "1..*" DriveProtectionSection
DriveProtectionSectionGroup *-- "1" ProtectedInfraElement
DriveProtectionSection *-- "1" infra.LinearElementSection
AllocationSection *-- "1" infra.NetLinearReference
FieldObjectController *-- "1..*" ControlledInfraElement
AreaOfControl *-- "1" infra.NetAreaReference
TrainProtectionArea *-- "*" DriveProtectionSectionGroup
TrainProtectionArea *-- "*" AllocationSection
TrainProtectionArea *-- "*" FieldObjectController
TrainProtectionArea *-- "1" AreaOfControl
TrainProtection *-- "*" TrainProtectionArea
@enduml