@startuml
skinparam monochrome true
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam DefaultFontName arial
skinparam DefaultFontSize 12
skinparam ClassFontStyle bold
skinparam linetype ortho
skinparam dpi 200
hide empty fields
hide empty methods
hide circle

class ProtectedInfraElement << union >> {
 switch: *infra.Switch
 slipCrossing: *infra.SlipCrossing
 crossing: *infra.Crossing
 derailer: *infra.Derailer
 levelCrossing: *infra.LevelCrossing
}

class DriveProtectionSectionGroup {
 id: string
 name: string[0..1]
 dependenciesType: DPSDependencyType
 dpsgDependencies: uint32[0..*]
 runTime: uint32
}

class DriveProtectionSection {
 id: string
 name: string
 maxFlankProtectionSpeed: uint32
}

class AllocationSection {
 id: string
 name: string[0..1]
 dependencies: *AllocationSection[1..*]
}

class ControlledInfraElement << union >> {
 dpsGroup: *DriveProtectionSectionGroup
 tvpSection: *infra.TvpSection
}

class FieldObjectController {
 id: string
 <b>belongsToAoc: *AreaOfControl</b>
 <s>rastaServerId: string</s>
 <s>rastaOCId: string</s>
 <s>version: uint32</s>
}

class AreaOfControl {
 id: string
 name: string[0..1]
}

class Controller {
 <b>id: string</b>
 <b>iPAddress: string[0..1]</b>
 <b>rastaId: string[0..1]</b>
 <b>portNumber: string[0..1]</b>
 <b>eulynxBaseline: string[0..1]</b>
 <b>version: uint32</b>
}

class RBCConfigurationPacket {
}

class ETCSMarker {
 <b>id: string</b>
 <b>markerType: MarkerFunction</b>
 <b>acknowledgementDistance: uint32[0..*]</b>
 <b>maxTransitionSpeed: uint32[0..*]</b>
 <b>offsetTransitionUnreachable: uint32[0..*]</b>
}

class TrainProtectionArea {
 id: string
 <s>routes: Route0..*</s>
 <s>switches: Switch0..*</s>
 <s>transits: Transit0..*</s>
}

class TrainProtection {
}

DriveProtectionSectionGroup *-- "1..*" DriveProtectionSection
DriveProtectionSectionGroup *-- "1" ProtectedInfraElement
DriveProtectionSection *-- "1" infra.LinearElementSection
AllocationSection *-- "1" infra.NetLinearReference
FieldObjectController *-- "1..*" ControlledInfraElement
FieldObjectController *-- "1" Controller
AreaOfControl *-- "1" infra.NetAreaReference
AreaOfControl *-- "0..1" Controller
RBCConfigurationPacket *-- "1" AreaOfControl
RBCConfigurationPacket *-- "1..*" infra.TopoArea
RBCConfigurationPacket *-- "1..*" infra.Switch
RBCConfigurationPacket *-- "0..*" infra.SlipCrossing
RBCConfigurationPacket *-- "0..*" infra.Crossing
RBCConfigurationPacket *-- "0..*" eng.BaliseGroup
RBCConfigurationPacket *-- "0..*" ETCSMarker
RBCConfigurationPacket *-- "1..*" infra.SampledLinearElementGeometry
RBCConfigurationPacket *-- "1..*" infra.LinearElementSpeedProfile
RBCConfigurationPacket *-- "1..*" map.Map
RBCConfigurationPacket *-- "0..*" infra.Bridge
RBCConfigurationPacket *-- "0..*" infra.LevelCrossing
RBCConfigurationPacket *-- "0..*" infra.TrackCondition
RBCConfigurationPacket *-- "0..*" infra.PlatformEdge
RBCConfigurationPacket *-- "1..*" eng.FoulingPoint
TrainProtectionArea *-- "0..*" DriveProtectionSectionGroup
TrainProtectionArea *-- "0..*" AllocationSection
TrainProtectionArea *-- "0..*" FieldObjectController
TrainProtectionArea *-- "0..*" AreaOfControl
TrainProtectionArea *-- "0..*" RBCConfigurationPacket
TrainProtectionArea *-- "0..*" ETCSMarker
TrainProtectionArea *-- "0..*" Controller
TrainProtection *-- "0..*" TrainProtectionArea
@enduml